### ISSUE TITLE
获取用户的任务列表时候的Page 参数如何传入？

### ISSUE THREAD

**Issue by clarkchen** [mycolorway/tower-api-document#1]
![image](https://user-images.githubusercontent.com/1352085/44647434-a63cc800-aa10-11e8-9d89-b63e5ce55d55.png)

不太清楚这个参数是如何传入的？

https://tower.im/api/v1/members/{member_id}/assigned_completed_todos?page=2

还是

https://tower.im/api/v1/members/{member_id}/assigned_completed_todos?page={ number: 2 }

无论请求那种现在提示我都是报错，但是如果把参数去掉了就正常了

![image](https://user-images.githubusercontent.com/1352085/44647597-0f244000-aa11-11e8-9dac-b04be9302a42.png)

**Comment by gavinliu** [comment]
是这样的：

```
https://tower.im/api/v1/members/{member_id}/assigned_completed_todos?page[number]=2
```


实际上你太不需要知道这些，你应该详细了解下 [json-api](http://jsonapi.org/) ，tower-api 是基于 json-api 构建的，在 json-api 的 links 节点会告诉你下一页的地址，这可能和其他厂商的 API 的分页不太一样。

**Comment by gavinliu** [comment]
是这样的：

```
https://tower.im/api/v1/members/{member_id}/assigned_completed_todos?page[number]=2
```


实际上你太不需要知道这些，你应该详细了解下 [json-api](http://jsonapi.org/) ，tower-api 是基于 json-api 构建的，在 json-api 的 links 节点会告诉你下一页的地址，这可能和其他 API 的分页不太一样。
